const fs = require('fs');
const path = require('path');

// Tables left over from an unrelated application in the imported dump.
const EXCLUDED = [/^oauth_/, /^orders$/, /^password_reset_temp$/, /^numseqtable$/];

function parseOut(argv) {
  const i = argv.indexOf('--out');
  return path.resolve(
    i >= 0 ? argv[i + 1] : path.join(__dirname, '..', '..', 'docs', 'schema.sql'),
  );
}

async function main() {
  const db = require('../config/db');
  const out = parseOut(process.argv);
  const conn = await db.createConnection();
  try {
    const [[{ name }]] = await conn.query('SELECT DATABASE() AS name');
    const [tables] = await conn.query(
      "SELECT table_name AS t FROM information_schema.tables WHERE table_schema = DATABASE() AND table_type = 'BASE TABLE' ORDER BY table_name",
    );
    const parts = [
      `-- Schema of \`${name}\`, generated by \`npm run db:schema\`. Do not edit by hand.`,
      '-- Structure only: no rows. Unrelated legacy tables are excluded.',
      '',
    ];
    for (const { t } of tables) {
      if (EXCLUDED.some((re) => re.test(t))) continue;
      const [[row]] = await conn.query(`SHOW CREATE TABLE \`${t}\``);
      // Auto-increment counters reflect data, not structure.
      parts.push(`${row['Create Table'].replace(/ AUTO_INCREMENT=\d+/, '')};`, '');
    }
    fs.writeFileSync(out, parts.join('\n'));
    console.log(`Wrote ${path.relative(process.cwd(), out)} from ${name}`);
  } finally {
    await conn.end();
  }
}

main().catch((err) => {
  console.error(`Schema dump failed: ${err.code || ''} ${err.message}`);
  process.exit(1);
});
