-- Schema of `csi_db`, generated by `npm run db:schema`. Do not edit by hand.
-- Structure only: no rows. Unrelated legacy tables are excluded.

CREATE TABLE `aqlplan` (
  `planid` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `inspectlevel` varchar(10) NOT NULL,
  `aql` varchar(20) NOT NULL,
  `isdefault` tinyint(1) NOT NULL DEFAULT 0,
  `note` varchar(255) DEFAULT NULL,
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`planid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `aqlplanrow` (
  `planid` int(11) NOT NULL,
  `inspectcategory` int(11) NOT NULL,
  `lotmin` int(11) NOT NULL,
  `lotmax` int(11) DEFAULT NULL,
  `codeletter` varchar(2) NOT NULL,
  `samplesize` int(11) NOT NULL,
  `acceptnum` int(11) NOT NULL,
  `rejectnum` int(11) NOT NULL,
  PRIMARY KEY (`planid`,`inspectcategory`,`lotmin`),
  CONSTRAINT `fk_aqlplanrow_plan` FOREIGN KEY (`planid`) REFERENCES `aqlplan` (`planid`) ON DELETE CASCADE,
  CONSTRAINT `chk_aqlplanrow_category` CHECK (`inspectcategory` in (1,2,3)),
  CONSTRAINT `chk_aqlplanrow_lot` CHECK (`lotmin` >= 1 and (`lotmax` is null or `lotmax` >= `lotmin`)),
  CONSTRAINT `chk_aqlplanrow_numbers` CHECK (`samplesize` >= 1 and `acceptnum` >= 0 and `rejectnum` > `acceptnum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `inspectline` (
  `inspectnum` varchar(30) NOT NULL,
  `linenum` int(11) NOT NULL,
  `inspecttype` varchar(50) DEFAULT NULL,
  `inspectitem` varchar(100) DEFAULT NULL,
  `standard_txt` varchar(100) DEFAULT NULL,
  `standard` decimal(18,2) DEFAULT NULL,
  `tolerance` decimal(18,2) DEFAULT 0.00,
  `tolerance_txt` varchar(50) DEFAULT NULL,
  `tolerance_plus` decimal(19,2) DEFAULT NULL,
  `tolerance_minus` decimal(19,2) DEFAULT NULL,
  `actual_1` decimal(18,2) DEFAULT NULL,
  `actual_2` decimal(18,2) DEFAULT NULL,
  `actual_3` decimal(18,2) DEFAULT NULL,
  `actual_4` decimal(18,2) DEFAULT NULL,
  `actual_5` decimal(18,2) DEFAULT NULL,
  `actual_6` decimal(18,2) DEFAULT NULL,
  `actual_7` decimal(18,2) DEFAULT NULL,
  `status_1` int(11) DEFAULT NULL,
  `status_2` int(11) DEFAULT NULL,
  `status_3` int(11) DEFAULT NULL,
  `status_4` int(11) DEFAULT NULL,
  `status_5` int(11) DEFAULT NULL,
  `status_6` int(11) DEFAULT NULL,
  `status_7` int(11) DEFAULT NULL,
  PRIMARY KEY (`inspectnum`,`linenum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `inspectlineother` (
  `inspectnum` varchar(30) NOT NULL,
  `linenum` int(11) NOT NULL,
  `inspecttype` varchar(30) DEFAULT NULL,
  `inspectitem` varchar(100) DEFAULT NULL,
  `standard_txt` varchar(100) DEFAULT NULL,
  `actual_txt_1` varchar(100) DEFAULT NULL,
  `actual_txt_2` varchar(100) DEFAULT NULL,
  `actual_txt_3` varchar(100) DEFAULT NULL,
  `actual_txt_4` varchar(100) DEFAULT NULL,
  `actual_txt_5` varchar(100) DEFAULT NULL,
  `actual_txt_6` varchar(100) DEFAULT NULL,
  `actual_txt_7` varchar(100) DEFAULT NULL,
  `status_1` int(11) DEFAULT NULL,
  `status_2` int(11) DEFAULT NULL,
  `status_3` int(11) DEFAULT NULL,
  `status_4` int(11) DEFAULT NULL,
  `status_5` int(11) DEFAULT NULL,
  `status_6` int(11) DEFAULT NULL,
  `status_7` int(11) DEFAULT NULL,
  PRIMARY KEY (`inspectnum`,`linenum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `inspectnumseq` (
  `prefix` varchar(10) NOT NULL,
  `digits` int(11) NOT NULL,
  `nextnum` int(11) NOT NULL,
  PRIMARY KEY (`prefix`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `inspectsetup` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `checkedby` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `inspecttable` (
  `inspectnum` varchar(30) NOT NULL,
  `inspectdate` date DEFAULT NULL,
  `itemid` varchar(30) DEFAULT NULL,
  `itemname` varchar(100) DEFAULT NULL,
  `accountnum` varchar(30) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `inspectstatus` varchar(30) DEFAULT NULL,
  `instrument` varchar(100) DEFAULT NULL,
  `purchordernum1` varchar(30) DEFAULT NULL,
  `purchordernum2` varchar(30) DEFAULT NULL,
  `purchordernum3` varchar(30) DEFAULT NULL,
  `purchordernum4` varchar(30) DEFAULT NULL,
  `purchordernum5` varchar(30) DEFAULT NULL,
  `purchordernum6` varchar(30) DEFAULT NULL,
  `purchordernum7` varchar(30) DEFAULT NULL,
  `deliverydate1` date DEFAULT current_timestamp(),
  `deliverydate2` date DEFAULT current_timestamp(),
  `deliverydate3` date DEFAULT current_timestamp(),
  `deliverydate4` date DEFAULT current_timestamp(),
  `deliverydate5` date DEFAULT current_timestamp(),
  `deliverydate6` date DEFAULT current_timestamp(),
  `deliverydate7` date DEFAULT current_timestamp(),
  `qty_received1` decimal(18,2) DEFAULT 0.00,
  `qty_received2` decimal(18,2) DEFAULT 0.00,
  `qty_received3` decimal(18,2) DEFAULT 0.00,
  `qty_received4` decimal(18,2) DEFAULT 0.00,
  `qty_received5` decimal(18,2) DEFAULT 0.00,
  `qty_received6` decimal(18,2) DEFAULT 0.00,
  `qty_received7` decimal(18,2) DEFAULT 0.00,
  `inspectcategory1` int(11) DEFAULT 0,
  `inspectcategory2` int(11) DEFAULT 0,
  `inspectcategory3` int(11) DEFAULT 0,
  `inspectcategory4` int(11) DEFAULT 0,
  `inspectcategory5` int(11) DEFAULT 0,
  `inspectcategory6` int(11) DEFAULT 0,
  `inspectcategory7` int(11) DEFAULT 0,
  `notgood1` int(11) DEFAULT 0,
  `notgood2` int(11) DEFAULT 0,
  `notgood3` int(11) DEFAULT 0,
  `notgood4` int(11) DEFAULT 0,
  `notgood5` int(11) DEFAULT 0,
  `notgood6` int(11) DEFAULT 0,
  `notgood7` int(11) DEFAULT 0,
  `judgment1` int(11) DEFAULT 0,
  `judgment2` int(11) DEFAULT 0,
  `judgment3` int(11) DEFAULT 0,
  `judgment4` int(11) DEFAULT 0,
  `judgment5` int(11) DEFAULT 0,
  `judgment6` int(11) DEFAULT 0,
  `judgment7` int(11) DEFAULT 0,
  `aqlplanid` int(11) DEFAULT NULL,
  `samplesize1` int(11) DEFAULT NULL,
  `samplesize2` int(11) DEFAULT NULL,
  `samplesize3` int(11) DEFAULT NULL,
  `samplesize4` int(11) DEFAULT NULL,
  `samplesize5` int(11) DEFAULT NULL,
  `samplesize6` int(11) DEFAULT NULL,
  `samplesize7` int(11) DEFAULT NULL,
  `acceptnum1` int(11) DEFAULT NULL,
  `acceptnum2` int(11) DEFAULT NULL,
  `acceptnum3` int(11) DEFAULT NULL,
  `acceptnum4` int(11) DEFAULT NULL,
  `acceptnum5` int(11) DEFAULT NULL,
  `acceptnum6` int(11) DEFAULT NULL,
  `acceptnum7` int(11) DEFAULT NULL,
  `rejectnum1` int(11) DEFAULT NULL,
  `rejectnum2` int(11) DEFAULT NULL,
  `rejectnum3` int(11) DEFAULT NULL,
  `rejectnum4` int(11) DEFAULT NULL,
  `rejectnum5` int(11) DEFAULT NULL,
  `rejectnum6` int(11) DEFAULT NULL,
  `rejectnum7` int(11) DEFAULT NULL,
  `concessionnote1` varchar(255) DEFAULT NULL,
  `concessionnote2` varchar(255) DEFAULT NULL,
  `concessionnote3` varchar(255) DEFAULT NULL,
  `concessionnote4` varchar(255) DEFAULT NULL,
  `concessionnote5` varchar(255) DEFAULT NULL,
  `concessionnote6` varchar(255) DEFAULT NULL,
  `concessionnote7` varchar(255) DEFAULT NULL,
  `qfnum` varchar(50) DEFAULT NULL,
  `inspectby` varchar(50) DEFAULT NULL,
  `inspectbyid` int(11) DEFAULT NULL,
  `checkedby` varchar(50) DEFAULT NULL,
  `recid` double DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`inspectnum`),
  KEY `idx_inspecttable_inspectdate` (`inspectdate`),
  KEY `idx_inspecttable_itemid` (`itemid`),
  KEY `idx_inspecttable_accountnum` (`accountnum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `inventinspectitem` (
  `itemid` varchar(30) NOT NULL,
  `itemname` varchar(100) DEFAULT NULL,
  `inspecttype` varchar(50) NOT NULL,
  `inspectitem` varchar(100) NOT NULL,
  `standard_txt` varchar(100) DEFAULT NULL,
  `standard` decimal(18,2) DEFAULT NULL,
  `tolerance` varchar(50) DEFAULT NULL,
  `tolerance_plus` decimal(19,2) DEFAULT 0.00,
  `tolerance_minus` decimal(19,2) DEFAULT 0.00,
  PRIMARY KEY (`itemid`,`inspecttype`,`inspectitem`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `inventtable` (
  `itemid` varchar(30) NOT NULL,
  `name` varchar(100) NOT NULL,
  `inspectqty` int(11) NOT NULL,
  PRIMARY KEY (`itemid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `schema_migrations` (
  `name` varchar(255) NOT NULL,
  `applied_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `usertable` (
  `userid` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `fullname` varchar(50) NOT NULL,
  `email` varchar(100) DEFAULT NULL,
  `role` varchar(20) NOT NULL,
  `password_hash` varchar(100) NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT 1,
  `must_change_password` tinyint(1) NOT NULL DEFAULT 0,
  `theme` varchar(10) NOT NULL DEFAULT 'light',
  `last_login_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`userid`),
  UNIQUE KEY `uq_usertable_username` (`username`),
  CONSTRAINT `chk_usertable_role` CHECK (`role` in ('INSPECTOR','CHECKER','ADMIN')),
  CONSTRAINT `chk_usertable_theme` CHECK (`theme` in ('light','dark','system'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `vendtable` (
  `vendaccount` varchar(30) NOT NULL,
  `name` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`vendaccount`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
